/*
 * Kuali Coeus, a comprehensive research administration system for higher education.
 * 
 * Copyright 2005-2015 Kuali, Inc.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.kuali.coeus.s2sgen.impl.generate.support;

import gov.grants.apply.forms.budgetV11.BudgetNarrativeAttachmentsDocument;
import gov.grants.apply.forms.budgetV11.BudgetNarrativeAttachmentsDocument.BudgetNarrativeAttachments;
import gov.grants.apply.system.attachmentsV10.AttachedFileDataType;
import gov.grants.apply.system.attachmentsV10.AttachmentGroupMin1Max100DataType;
import org.apache.xmlbeans.XmlObject;
import org.kuali.coeus.propdev.api.core.ProposalDevelopmentDocumentContract;
import org.kuali.coeus.propdev.api.attachment.NarrativeContract;
import org.kuali.coeus.s2sgen.impl.generate.FormGenerator;
import org.kuali.coeus.s2sgen.impl.generate.FormVersion;
import org.kuali.coeus.s2sgen.impl.generate.S2SBaseFormGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;


import java.util.ArrayList;
import java.util.List;

/**
 * 
 * This class is used to generate XML Document object for grants.gov BudgetV1.1. This form is generated using XMLBean API's
 * generated by compiling BudgetV1.1 schema.
 * 
 * @author Kuali Research Administration Team (kualidev@oncourse.iu.edu)
 */
@FormGenerator("BudgetV1_1Generator")
public class BudgetV1_1Generator extends S2SBaseFormGenerator {

    private static final Logger LOG = LoggerFactory.getLogger(ProjectV1_0Generator.class);
    private static final int BUDGET_ATTACHMENTS = 57;

    @Value("http://apply.grants.gov/forms/Budget-V1.1")
    private String namespace;

    @Value("Budget-V1.1")
    private String formName;

    @Value("classpath:org/kuali/coeus/s2sgen/impl/generate/support/stylesheet/Budget-V1.1.fo.xsl")
    private Resource stylesheet;

    @Value("gov.grants.apply.forms.BudgetV11")
    private String packageName;

    @Value(DEFAULT_SORT_INDEX)
    private int sortIndex;

    /**
     * 
     * This method is used to get Narrative Attachments for Particular Budget
     * 
     * @return budgetNarrativeAttachmentsDocument(BudgetNarrativeAttachmentsDocument) {@link XmlObject} of type
     *         BudgetNarrativeAttachmentsDocument.
     */
    private BudgetNarrativeAttachmentsDocument getBudgetNarrativeAttachmentsDocument() {

        BudgetNarrativeAttachmentsDocument budgetNarrativeAttachmentsDocument = BudgetNarrativeAttachmentsDocument.Factory
                .newInstance();
        BudgetNarrativeAttachments budgetNarrativeAttachments = BudgetNarrativeAttachments.Factory.newInstance();
        budgetNarrativeAttachments.setFormVersion(FormVersion.v1_1.getVersion());

        AttachmentGroupMin1Max100DataType attachmentGroupMin1Max100DataType = AttachmentGroupMin1Max100DataType.Factory
                .newInstance();
        attachmentGroupMin1Max100DataType.setAttachedFileArray(getAttachedFileDataTypes());
        budgetNarrativeAttachments.setAttachments(attachmentGroupMin1Max100DataType);

        budgetNarrativeAttachmentsDocument.setBudgetNarrativeAttachments(budgetNarrativeAttachments);
        return budgetNarrativeAttachmentsDocument;
    }

    /**
     * 
     * This method is used to get List of attachments from NarrativeAttachment
     * 
     * @return attachedFileDataTypes(AttachedFileDataType[])- returns an array of AttachedFileDataType if the NarrativeTypeCode is
     *         BUDGET_ATTACHMENTS
     */
    private AttachedFileDataType[] getAttachedFileDataTypes() {
        LOG.debug("Getting AttachedFileDataType ");
        List<AttachedFileDataType> attachedFileDataTypes = new ArrayList<AttachedFileDataType>();
        AttachedFileDataType attachedFileDataType = null;
        for (NarrativeContract narrative : pdDoc.getDevelopmentProposal().getNarratives()) {
            if (narrative.getNarrativeType().getCode() != null
                    && Integer.parseInt(narrative.getNarrativeType().getCode()) == BUDGET_ATTACHMENTS ) {
            	attachedFileDataType = getAttachedFileType(narrative);
            	if (attachedFileDataType != null) {
					attachedFileDataTypes.add(attachedFileDataType);
					LOG.debug("Attachmentcount" + attachedFileDataTypes.size());
				}
            }
        }
        return attachedFileDataTypes.toArray(new AttachedFileDataType[0]);
    }

    /**
     * This method creates {@link XmlObject} of type {@link BudgetNarrativeAttachmentsDocument} by populating data from the given
     * {@link ProposalDevelopmentDocumentContract}
     * 
     * @param proposalDevelopmentDocument for which the {@link XmlObject} needs to be created
     * @return {@link XmlObject} which is generated using the given {@link ProposalDevelopmentDocumentContract}
     */
    public XmlObject getFormObject(ProposalDevelopmentDocumentContract proposalDevelopmentDocument) {
        this.pdDoc = proposalDevelopmentDocument;
        return getBudgetNarrativeAttachmentsDocument();
    }

    @Override
    public String getNamespace() {
        return namespace;
    }

    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    @Override
    public String getFormName() {
        return formName;
    }

    public void setFormName(String formName) {
        this.formName = formName;
    }

    @Override
    public Resource getStylesheet() {
        return stylesheet;
    }

    public void setStylesheet(Resource stylesheet) {
        this.stylesheet = stylesheet;
    }

    @Override
    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    @Override
    public int getSortIndex() {
        return sortIndex;
    }

    public void setSortIndex(int sortIndex) {
        this.sortIndex = sortIndex;
    }
}
