/*
 * Kuali Coeus, a comprehensive research administration system for higher education.
 * 
 * Copyright 2005-2015 Kuali, Inc.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.kuali.coeus.s2sgen.impl.generate.support;

import gov.grants.apply.forms.nsfDeviationAuthorizationV11.NSFDeviationAuthorizationDocument;
import gov.grants.apply.forms.nsfDeviationAuthorizationV11.NSFDeviationAuthorizationDocument.NSFDeviationAuthorization;
import org.apache.xmlbeans.XmlObject;

import org.kuali.coeus.s2sgen.impl.generate.FormGenerator;
import org.kuali.coeus.propdev.api.core.ProposalDevelopmentDocumentContract;
import org.kuali.coeus.s2sgen.impl.generate.FormVersion;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;


/**
 * 
 * This class is used to generate XML Document object for grants.gov NSFDeviationAuthorizationV1.1. This form is generated using
 * XMLBean API's generated by compiling NSFDeviationAuthorizationV1.1 schema.
 * 
 * @author Kuali Research Administration Team (kualidev@oncourse.iu.edu)
 */
@FormGenerator("NSFDeviationAuthorizationV1_1Generator")
public class NSFDeviationAuthorizationV1_1Generator extends NSFDeviationAuthorizationBaseGenerator {

    @Value("http://apply.grants.gov/forms/NSF_DeviationAuthorization-V1.1")
    private String namespace;

    @Value("NSF_DeviationAuthorization-V1.1")
    private String formName;

    @Value("classpath:org/kuali/coeus/s2sgen/impl/generate/support/stylesheet/NSF_DeviationAuthorization-V1.1.fo.xsl")
    private Resource stylesheet;

    @Value("gov.grants.apply.forms.nsfDeviationAuthorizationV11")
    private String packageName;

    @Value(DEFAULT_SORT_INDEX)
    private int sortIndex;


    /**
     * 
     * This method returns NSFDeviationAuthorizationDocument object based on proposal development document which contains the
     * NSFDeviationAuthorizationDocument information NSFDeviationAuthorization for a particular proposal
     * 
     * @return authorizationDocument {@link XmlObject} of type NSFDeviationAuthorizationDocument.
     */
    private NSFDeviationAuthorizationDocument getNSFDeviationAuthorization() {

        NSFDeviationAuthorizationDocument authorizationDocument = NSFDeviationAuthorizationDocument.Factory.newInstance();
        NSFDeviationAuthorization nsfDeviationAuthorization = NSFDeviationAuthorization.Factory.newInstance();
        nsfDeviationAuthorization.setFormVersion(FormVersion.v1_1.getVersion());
        String devAuth = getAbstractText(DEVIATION_AUTHORIZATION);
        if (devAuth != null) {
            nsfDeviationAuthorization.setDeviationAuthorization(devAuth);
        }
        authorizationDocument.setNSFDeviationAuthorization(nsfDeviationAuthorization);
        return authorizationDocument;
    }

    /**
     * This method creates {@link XmlObject} of type {@link NSFDeviationAuthorizationDocument} by populating data from the given
     * {@link ProposalDevelopmentDocumentContract}
     * 
     * @param proposalDevelopmentDocument for which the {@link XmlObject} needs to be created
     * @return {@link XmlObject} which is generated using the given {@link ProposalDevelopmentDocumentContract}
     */
    public XmlObject getFormObject(ProposalDevelopmentDocumentContract proposalDevelopmentDocument) {
        this.pdDoc = proposalDevelopmentDocument;
        return getNSFDeviationAuthorization();
    }

    @Override
    public String getNamespace() {
        return namespace;
    }

    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    @Override
    public String getFormName() {
        return formName;
    }

    public void setFormName(String formName) {
        this.formName = formName;
    }

    @Override
    public Resource getStylesheet() {
        return stylesheet;
    }

    public void setStylesheet(Resource stylesheet) {
        this.stylesheet = stylesheet;
    }

    @Override
    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    @Override
    public int getSortIndex() {
        return sortIndex;
    }

    public void setSortIndex(int sortIndex) {
        this.sortIndex = sortIndex;
    }
}
